### ISSUE TITLE
When I click on  option acccount GoogleAccountCredential issue.

### ISSUE THREAD

**Issue by NirajRaval** [youtube/yt-direct-lite-android#16]
FATAL EXCEPTION: main
                                                                 Process: com.google.ytdl, PID: 11678
                                                                 java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Intent com.google.api.client.googleapis.extensions.android.gms.auth.GoogleAccountCredential.newChooseAccountIntent()' on a null object reference
                                                                     at com.google.ytdl.MainActivity.chooseAccount(MainActivity.java:582)
                                                                     at com.google.ytdl.MainActivity.onOptionsItemSelected(MainActivity.java:289)
                                                                     at android.app.Activity.onMenuItemSelected(Activity.java:2895)
                                                                     at com.android.internal.policy.impl.PhoneWindow.onMenuItemSelected(PhoneWindow.java:1133)
                                                                     at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:761)
                                                                     at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:152)
                                                                     at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:904)
                                                                     at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:894)
                                                                     at com.android.internal.view.menu.MenuPopupHelper.onItemClick(MenuPopupHelper.java:186)
                                                                     at android.widget.AdapterView.performItemClick(AdapterView.java:305)
                                                                     at android.widget.AbsListView.performItemClick(AbsListView.java:1146)
                                                                     at android.widget.AbsListView$PerformClick.run(AbsListView.java:3053)
                                                                     at android.widget.AbsListView$3.run(AbsListView.java:3860)
                                                                     at android.os.Handler.handleCallback(Handler.java:739)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                     at android.os.Looper.loop(Looper.java:135)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5343)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at java.lang.reflect.Method.invoke(Method.java:372)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
04-14 17:59:07.260 11678-11678/com.google.ytdl I/Process: Sending signal. PID: 11678 SIG: 9

**Comment by palashjaincarpathy** [comment]
Same issue, have you got the solution?
if yes then please tell me.
